<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use DateTimeInterface;

class ExportLocalContent extends Command
{
    protected $signature = 'content:export {--path=database/local-content.sql : Output SQL file}';

    protected $description = 'Export editorial database content for deployment';

    /** @var list<string> */
    private array $tables = [
        'certifications',
        'hero_slides',
        'karma_departments',
        'leadership_members',
        'media_assets',
        'news',
        'partners',
        'press_documents',
        'reports',
        'site_settings',
    ];

    public function handle(): int
    {
        $outputPath = base_path((string) $this->option('path'));
        $pdo = DB::connection()->getPdo();
        $sql = [
            '-- Generated by php artisan content:export',
            '-- Editorial content only. Users, sessions and applications are excluded.',
            'SET client_encoding = \'UTF8\';',
            'SET standard_conforming_strings = on;',
            '',
        ];

        foreach ($this->tables as $table) {
            if (! Schema::hasTable($table)) {
                continue;
            }

            $columns = Schema::getColumnListing($table);
            $quotedTable = $this->quoteIdentifier($table);
            $quotedColumns = implode(', ', array_map([$this, 'quoteIdentifier'], $columns));
            $rows = DB::table($table)->orderBy($columns[0])->get();

            $sql[] = "-- Data for {$table}";
            foreach ($rows as $row) {
                $values = [];
                foreach ($columns as $column) {
                    $values[] = $this->quoteValue($pdo, $row->{$column});
                }

                $sql[] = "INSERT INTO {$quotedTable} ({$quotedColumns}) VALUES (" . implode(', ', $values) . ');';
            }

            if (in_array('id', $columns, true)) {
                $sequence = DB::selectOne(
                    "SELECT pg_get_serial_sequence(?, 'id') AS sequence",
                    ["public.{$table}"],
                )?->sequence;

                if ($sequence) {
                    $quotedSequence = $pdo->quote($sequence);
                    $sql[] = "SELECT pg_catalog.setval({$quotedSequence}, COALESCE((SELECT MAX(\"id\") FROM {$quotedTable}), 1), (SELECT COUNT(*) > 0 FROM {$quotedTable}));";
                }
            }

            $sql[] = '';
        }

        if (file_put_contents($outputPath, implode(PHP_EOL, $sql) . PHP_EOL) === false) {
            $this->error("Unable to write {$outputPath}");
            return self::FAILURE;
        }

        $this->info("Exported editorial content to {$outputPath}");
        return self::SUCCESS;
    }

    private function quoteIdentifier(string $identifier): string
    {
        return '"' . str_replace('"', '""', $identifier) . '"';
    }

    private function quoteValue(\PDO $pdo, mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $value ? 'TRUE' : 'FALSE';
        }

        if ($value instanceof DateTimeInterface) {
            $value = $value->format('Y-m-d H:i:s.uP');
        }

        return $pdo->quote((string) $value);
    }
}
