-- SQL Export from Néré Mining local database
-- Import this into production database - includes data only
-- Generated: 2026-09-11 

-- Insert data
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (1, 'carousel_autoplay', 'true', 'boolean', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (2, 'carousel_interval', '5000', 'number', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (3, 'carousel_transition_speed', '800', 'number', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (4, 'carousel_pause_on_hover', 'true', 'boolean', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (5, 'carousel_show_indicators', 'true', 'boolean', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (6, 'carousel_show_arrows', 'true', 'boolean', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (7, 'site_name', 'Néré Mining', 'string', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (8, 'contact_email', 'contact@nere-mining.bf', 'string', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (9, 'contact_phone', '+226 XX XX XX XX', 'string', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (10, 'maintenance_mode', 'false', 'boolean', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (11, 'analytics_enabled', 'true', 'boolean', NOW(), NOW());
INSERT INTO site_settings (id, key, value, type, created_at, updated_at) VALUES (12, 'newsletter_enabled', 'true', 'boolean', NOW(), NOW());

INSERT INTO users (id, name, email, password, is_admin, public_uuid, created_at, updated_at) VALUES (1, 'Administrateur Néré Mining', 'admin@nere-mining.bf', '$2y$12$7pzHFoElOUCEtLfM4hvz0eOgrTPZJXqiDq15uj2dSteujIY7NvJfa', true, '17696c08-88aa-4156-9116-5b757cfbbb4c', NOW(), NOW());

INSERT INTO hero_slides (id, title, caption, image_path, is_active, sort_order, type, created_at, updated_at) VALUES (1, '', 'Une entreprise minière à ancrage national', 'images/hero/7I0F6l1lmLkgswXMdTDm4ayucFaHUgcMJcnzn0im.jpg', true, 0, 'image', NOW(), NOW());
INSERT INTO hero_slides (id, title, caption, image_path, is_active, sort_order, type, created_at, updated_at) VALUES (2, '', 'Une mine en exploitation : Riverstone Karma', 'images/hero/H7eEolBtJlKwU8I1VCj8iU4g6G0cNthAfc55kopr.jpg', true, 1, 'image', NOW(), NOW());
INSERT INTO hero_slides (id, title, caption, image_path, is_active, sort_order, type, created_at, updated_at) VALUES (3, '', 'Des activités d''exploration et un portefeuille en développement', 'images/hero/UCrXfKr1OeYXovqWbAyM48WdKySdWoGQgpc99SGs.jpg', true, 2, 'image', NOW(), NOW());
INSERT INTO hero_slides (id, title, caption, image_path, is_active, sort_order, type, created_at, updated_at) VALUES (4, '', 'Une ambition fondée sur la performance, la responsabilité et la création de valeur partagée', 'images/hero/Aqlk75ywPYBXsQWFa0Z7pRFKAdLsajbcqDPSY3FV.jpg', true, 3, 'image', NOW(), NOW());

INSERT INTO partners (id, name, logo_path, category, is_published, sort_order, created_at, updated_at) VALUES (1, 'NEMMBA', 'images/partners/sqPw83NAqaqnNgAWob1Dy9viOh4uJAcpjPYFQzgq.jpg', 'TECHNIQUE', true, 1, NOW(), NOW());
INSERT INTO partners (id, name, logo_path, category, is_published, sort_order, created_at, updated_at) VALUES (2, 'NEEMBA', 'images/partners/neemba-cat.jpg', 'ÉQUIPEMENT', true, 2, NOW(), NOW());

INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (1, 'Administration', 'Administration', 'Administration de la mine', 'Mine Administration', 'Planification stratégique, gestion des opérations, supervision financière et conformité réglementaire.', 'Strategic planning, operations management, financial supervision and regulatory compliance.', 1, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (2, 'Ressources humaines', 'Human Resources', 'Ressources humaines', 'Human Resources', 'Les ressources humaines gèrent le personnel et contribuent à garantir un environnement de travail productif, sûr et épanouissant.', 'Human resources manage personnel and help ensure a productive, safe and fulfilling work environment.', 2, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (3, 'Sûreté', 'Security', 'Département Sécurité', 'Security Department', 'Le dispositif comprend une CCTV de 44 caméras, une cellule drone, une brigade canine, une permanence des superviseurs 24h/24.', 'The security system includes 44 CCTV cameras, a drone unit, a canine brigade, and 24/7 supervisor presence.', 3, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (4, 'Opérations', 'Operations', 'Département Mining', 'Mining Department', 'Le processus minier regroupe la planification, les études de faisabilité, l''analyse économique et les étapes techniques.', 'The mining process includes planning, feasibility studies, economic analysis and technical steps.', 4, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (5, 'HSE', 'HSE', 'Hygiène, Santé, Sécurité et Environnement', 'Health, Safety, Security and Environment', 'Le département HSE vise zéro incident grâce à la formation continue, aux inspections régulières, au suivi environnemental.', 'The HSE department aims for zero incidents through continuous training, regular inspections, and environmental monitoring.', 5, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (6, 'Traitement', 'Processing', 'Département Processing', 'Processing Department', 'Le Processing est organisé en quatre sections : opérations, maintenance des équipements fixes, métallurgie et infrastructures.', 'Processing is organized into four sections: operations, fixed equipment maintenance, metallurgy and infrastructure.', 6, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (7, 'Approvisionnement', 'Supply Chain', 'Chaîne d''approvisionnement (SCM)', 'Supply Chain Management (SCM)', 'Le SCM comprend les Achats, la Logistique, les Contrats et le Magasin. Il est dirigé par une équipe entièrement locale.', 'SCM includes Purchasing, Logistics, Contracts and Warehouse. It is managed by an entirely local team.', 7, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (8, 'Technologies', 'IT', 'Département IT', 'IT Department', 'Le département IT accompagne les équipes et les opérations de Karma grâce aux outils et services numériques.', 'The IT department supports Karma''s teams and operations through digital tools and services.', 8, true, NOW(), NOW());
INSERT INTO karma_departments (id, tag_fr, tag_en, title_fr, title_en, body_fr, body_en, sort_order, is_published, created_at, updated_at) VALUES (9, 'Dialogue local', 'Community Relations', 'Relations communautaires', 'Community Relations', 'Le département gère les impacts sociaux, entretient le dialogue avec les communautés et soutient les autorités locales.', 'The department manages social impacts, maintains dialogue with communities and supports local authorities.', 9, true, NOW(), NOW());

INSERT INTO leadership_members (id, name, title, department, photo_path, is_published, sort_order, hierarchy_level, created_at, updated_at) VALUES (1, 'Dr. Justin Elie OUEDRAOGO', 'Président Directeur Général', NULL, 'images/leadership/pdg-traditional.jpg', true, 1, 1, NOW(), NOW());
INSERT INTO leadership_members (id, name, title, department, photo_path, is_published, sort_order, hierarchy_level, created_at, updated_at) VALUES (2, 'Justin SAVADOGO', 'Directeur Général Adjoint', 'Administration & Finance', 'images/leadership/placeholder.jpg', true, 2, 2, NOW(), NOW());
INSERT INTO leadership_members (id, name, title, department, photo_path, is_published, sort_order, hierarchy_level, created_at, updated_at) VALUES (3, 'Pascal Y. OUEDRAOGO', 'Directeur Général Adjoint', 'Approvisionnements', 'images/leadership/placeholder.jpg', true, 3, 2, NOW(), NOW());
INSERT INTO leadership_members (id, name, title, department, photo_path, is_published, sort_order, hierarchy_level, created_at, updated_at) VALUES (4, 'Laurent Michel DABIRE', 'Directeur Général Adjoint', 'Affaires Corporatives & Juridiques', 'images/leadership/placeholder.jpg', true, 4, 2, NOW(), NOW());
INSERT INTO leadership_members (id, name, title, department, photo_path, is_published, sort_order, hierarchy_level, created_at, updated_at) VALUES (5, 'Augustine OBENG-FORI', 'DGA par intérim', 'Opérations', 'images/leadership/placeholder.jpg', true, 5, 2, NOW(), NOW());

INSERT INTO news (id, title, category, excerpt, image_path, published_at, created_at, updated_at) VALUES (1, 'Annulation du contrat d''achat d''or: Riverstone Karma SA salue une décision judiciaire historique du Tribunal de commerce de Ouagadougou', 'Actualités', 'Par jugement en date du 10 juin 2026, le Tribunal de commerce de Ouagadougou a statué en faveur de Riverstone Karma SA dans le différend qui l''opposait aux sociétés Franco-Nevada et Sandstorm Gold Ltd.', 'images/news/ZJ58L6cbb9z6C4qPwArMnxzy0A4RQW4doJDfc7SV.jpg', '2026-08-12', NOW(), NOW());
INSERT INTO news (id, title, category, excerpt, image_path, published_at, created_at, updated_at) VALUES (2, 'Forum Mines 2026 : Néré Mining réaffirme son engagement en faveur des pratiques durables dans l''exploitation minière', 'Événement', 'La troisième édition du Forum Mines a officiellement ouvert ses portes le mardi 7 juillet 2026 à Ouagadougou.', 'images/news/g4XciRGY5t48TKSsjdneCu5APzh3g673Q30YMnpr.jpg', '2026-08-22', NOW(), NOW());
INSERT INTO news (id, title, category, excerpt, image_path, published_at, created_at, updated_at) VALUES (3, '6ème édition de la SAMAO.', 'Partenariats', 'Nous renforçons nos partenariats avec les entreprises et organisations locales pour créer de la valeur partagée.', 'images/news/F6nUuFafpUqWZu1MKDcY5PzQbQsDXsFMXmEOVNuX.png', '2024-11-29', NOW(), NOW());