services:
  - type: web
    name: nere-mining
    runtime: php
    region: fra
    plan: free
    buildCommand: composer install --no-dev --prefer-dist
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LARAVEL_LOG_CHANNEL
        value: stdout
