TRUNCATE TABLE `news` CASCADE;
INSERT INTO `news` (`id`, `title`, `category`, `excerpt`, `image_path`, `published_at`, `created_at`, `updated_at`, `content`, `slug`, `gallery_images`) VALUES (1, 'Annulation du contrat d\'achat d\'or : Riverstone Karma SA salue une décision judiciaire historique', 'Gouvernance', 'Par jugement en date du 10 juin 2026, le Tribunal de commerce de Ouagadougou a statué en faveur de Riverstone Karma SA dans le différend qui l’opposait aux sociétés Franco-Nevada et Sandstorm Gold Ltd (aujourd’hui IRC).', 'news/FygENNJr36vgw9vcHOKKRXXjCM3R2t5pFsWppYO8.jpg', '2026-07-20 00:00:00', '2026-09-07 13:52:26', '2026-09-08 07:53:22', 'La juridiction a prononcé l’annulation du Gold Purchase Agreement (GPA), un contrat d’achat d’or conclu en 2014, et a condamné solidairement les deux sociétés à verser à Riverstone Karma SA la somme de 5 218 224 600 francs CFA (environ 9,3 millions de dollars américains) à titre de réparation.

Hérité d’un montage financier mis en place plusieurs années avant la reprise de la mine de Karma en 2022, le contrat imposait des engagements de long terme particulièrement contraignants sur la commercialisation de la production aurifère. Ces dispositions limitaient la flexibilité financière de l’exploitation et réduisaient sa capacité à mobiliser les ressources nécessaires pour son développement.

L’annulation de ce contrat permet aujourd’hui à Riverstone Karma SA de retrouver une plus grande autonomie dans la gestion de ses ressources et de maximiser les retombées économiques au bénéfice du Burkina Faso. Elle réaffirme également l’importance du respect du cadre juridique burkinabè et des principes économiques et financiers de l’Union économique et monétaire ouest-africaine (UEMOA).

Cette nouvelle dynamique favorisera notamment :

Le renforcement des investissements productifs ;
L’optimisation des recettes fiscales et des dividendes versés à l’État ;
La création de valeur pour les partenaires nationaux ;
Le développement des opportunités économiques au profit des communautés locales ;
La consolidation d’une exploitation minière durable.
Riverstone Karma SA réaffirme son engagement à promouvoir une exploitation minière responsable, fondée sur le respect des lois nationales et des meilleures pratiques internationales. La société poursuivra ses investissements afin de créer de la valeur durable pour l’ensemble de ses parties prenantes.', 'annulation-du-contrat-dachat-dor-riverstone-karma-sa-salue-une-decision-judiciaire-historique', NULL);
INSERT INTO `news` (`id`, `title`, `category`, `excerpt`, `image_path`, `published_at`, `created_at`, `updated_at`, `content`, `slug`, `gallery_images`) VALUES (2, 'Forum Mines 2026 : Néré Mining réaffirme son engagement en faveur des pratiques durables dans l\'exploitation minière', 'HSE', 'La troisième édition du Forum Mines a officiellement ouvert ses portes le mardi 7 juillet 2026 à Ouagadougou. Organisée par la Chambre des mines du Burkina, cette rencontre s’est déroulée du 7 au 9 juillet autour du thème : « Santé, sécurité et environnement : libérer le plein potentiel minier », sous le patronage du président de l’Assemblée législative du peuple.', 'news/nqMGQxXF6WivCvIrGEXI5nCQ1iMBv2DDIZky3vpH.jpg', '2026-07-16 00:00:00', '2026-09-07 13:52:26', '2026-09-08 07:55:04', 'Parmi les entreprises présentes au Forum Mines 2026 figure Riverstone Karma SA, détenue par la société Néré Mining. Elle est venue réaffirmer son engagement en matière de santé, de sécurité et d’environnement (HSE). Pour elle, cette participation constitue une occasion privilégiée de partager les expériences du secteur et de renforcer les bonnes pratiques.

Selon Esaie Sawadogo, chargé de santé et sécurité à Riverstone Karma, la présence de l’entreprise à cette édition s’inscrit dans une volonté de contribuer activement aux réflexions sur les enjeux du secteur. «La santé et la sécurité constituent un pilier essentiel au bon fonctionnement d’une industrie, particulièrement dans le secteur minier. Il était de notre devoir de prendre part à cette rencontre afin d’échanger sur les défis à relever et de contribuer au renforcement de la culture santé-sécurité », a-t-il expliqué.

Après avoir acquis la mine de Karma en 2022, Néré Mining se distingue comme la première société minière de droit burkinabé, détenue par des actionnaires majoritairement nationaux. En participant au forum, l’entreprise met également en lumière ses projets à travers un stand d’exposition ouvert aux visiteurs. Les représentants de Néré Mining ont également pris part à plusieurs panels consacrés aux questions de santé, de sécurité et d’environnement. Ces échanges ont permis de découvrir les expériences d’autres sociétés minières ainsi que les évolutions des textes réglementaires en vigueur dans le domaine du HSE.« Nous repartons satisfaits de ces échanges. Les expériences partagées et les conseils reçus nous permettront d’améliorer davantage nos pratiques afin de garantir un environnement de travail toujours plus sûr », a confié M. Sawadogo.

À l’endroit des acteurs du secteur et des entreprises burkinabè, il a lancé un appel à faire de la santé et de la sécurité une priorité. « Le capital humain demeure la première richesse de toute entreprise. Il est indispensable de mettre en place un système HSE efficace afin d’offrir aux travailleurs des conditions de travail sûres et favorables à leur productivité », a-t-il conclu.

À travers cette participation, Néré Mining confirme sa volonté de promouvoir une culture de prévention et d’amélioration continue, en cohérence avec les objectifs du Forum Mines 2026 pour un secteur minier plus performant, plus responsable et plus sûr.', 'forum-mines-2026-nere-mining-reaffirme-son-engagement-en-faveur-des-pratiques-durables-dans-lexploitation-miniere', NULL);
INSERT INTO `news` (`id`, `title`, `category`, `excerpt`, `image_path`, `published_at`, `created_at`, `updated_at`, `content`, `slug`, `gallery_images`) VALUES (3, 'Semaine des Activités Minières de l\'Afrique de l\'Ouest', 'Événement', 'Retour sur la 6e édition de la SAMAO, consacrée aux stratégies de développement liées aux minéraux critiques pour les pays africains.', 'news/ClY1vOlgljZlrcugFSlfM4T6EBT019H7QBRyioKu.png', '2024-11-29 00:00:00', '2026-09-07 13:52:26', '2026-09-08 07:54:05', 'MOT DU PARRAIN
Je voudrais exprimer mes vifs remerciements à l’endroit du Gouvernement du Burkina Faso pour le choix porté sur ma modeste personne pour parrainer cette 6 ème édition de la SAMAO.

Le thème de cette rencontre « Les minéraux critiques : Quelles stratégies de développement pour les pays africains ? » est d’un intérêt stratégique pour « réaliser l’Afrique que nous voulons, c’est à dire une Afrique qui compte et qui gagne».

Des premières Journées de Promotion des activités minières (PROMIN en 1995) à la SAMAO 2024, que de chemin parcouru !!!! Quel engagement soutenu et quelle belle détermination du Gouvernement, des acteurs privés, de la société civile et des  Partenaires techniques et financiers, à faire du secteur minier, un puissant levier de développement économique et social de nos chers pays !!!

Notre vision, notre ambition et notre engagement dans le secteur minier est d’en faire un véritable accélérateur de l’industrialisation de notre continent et de créer des chaines de valeurs par une approche intégrée basée sur la diversification et le développement de son incommensurable potentiel géologique, la valeur de ses ressources humaines, la création de richesses et le soutien aux petites et moyennes entreprises, en vue de leur insertion dans l’économie minière.

Les thématiques abordées durant ces trois jours à l’ère de la transition énergétique constituent autant de défis qu’il nous faut relever ensemble, si nous voulons faire de l’Afrique le Continent de l’avenir. Certes, beaucoup a été fait mais beaucoup reste encore à parfaire. Et comme une termitière vivante, ajoutons toujours de la terre à la terre. Je terminerai enfin, en souhaitant plein succès à la SAMAO 2024 et en félicitant toutes les parties prenantes dans l’Organisation de cet important évènement continental qui démontre une fois de plus le rôle prépondérant de notre cher pays dans le concert des plus grandes nations minières.

NAAABA BAOOGO DE GOURCY

PDG de NERE MINING SA', 'semaine-des-activites-minieres-de-lafrique-de-louest', NULL);

TRUNCATE TABLE `partners` CASCADE;
INSERT INTO `partners` (`id`, `name`, `logo_path`, `website_url`, `category`, `is_published`, `sort_order`, `created_at`, `updated_at`) VALUES (1, 'NEMMBA', 'partners/pMc5uaRdviLRriZMxGeV9Mg6QzLvxGDv0bnK54tW.jpg', NULL, 'TECHNIQUE', 1, 4, '2026-09-08 07:56:37', '2026-09-08 07:56:37');

TRUNCATE TABLE `hero_slides` CASCADE;
INSERT INTO `hero_slides` (`id`, `title`, `caption`, `image_path`, `is_active`, `sort_order`, `created_at`, `updated_at`, `type`, `video_url`) VALUES (6, 'Une mine de classe mondiale', NULL, 'images/carousel/gyathursan-mine-5523376_1920.jpg', 1, 0, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 'image', NULL);
INSERT INTO `hero_slides` (`id`, `title`, `caption`, `image_path`, `is_active`, `sort_order`, `created_at`, `updated_at`, `type`, `video_url`) VALUES (7, 'Des opérations responsables', NULL, 'images/carousel/pexels-gunshe-5125104.jpg', 1, 1, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 'image', NULL);
INSERT INTO `hero_slides` (`id`, `title`, `caption`, `image_path`, `is_active`, `sort_order`, `created_at`, `updated_at`, `type`, `video_url`) VALUES (8, 'L’excellence industrielle', NULL, 'images/carousel/shibang-mechanical-2653706_1920.jpg', 1, 2, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 'image', NULL);
INSERT INTO `hero_slides` (`id`, `title`, `caption`, `image_path`, `is_active`, `sort_order`, `created_at`, `updated_at`, `type`, `video_url`) VALUES (9, 'Des équipes engagées', NULL, 'images/carousel/tyna_janoch-excavator-2781676_1920.jpg', 1, 3, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 'image', NULL);
INSERT INTO `hero_slides` (`id`, `title`, `caption`, `image_path`, `is_active`, `sort_order`, `created_at`, `updated_at`, `type`, `video_url`) VALUES (10, 'Un territoire en mouvement', NULL, 'images/carousel/tyna_janoch-mine-2781686_1920.jpg', 1, 4, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 'image', NULL);
INSERT INTO `hero_slides` (`id`, `title`, `caption`, `image_path`, `is_active`, `sort_order`, `created_at`, `updated_at`, `type`, `video_url`) VALUES (17, 'Karma, notre mine d’or', NULL, 'images/carousel/Video Project 1.mp4', 1, 5, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 'video', NULL);

TRUNCATE TABLE `karma_departments` CASCADE;
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (1, 'Administration', 'Administration', 'Administration de la mine', 'Mine Administration', 'Planification stratégique, gestion des opérations, supervision financière et conformité réglementaire. L\'administration coordonne les départements et les services techniques, HSE et ressources humaines.', 'Strategic planning, operations management, financial oversight and regulatory compliance. Administration coordinates the technical, HSE and human resources departments.', 1, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (2, 'Ressources humaines', 'Human resources', 'Ressources humaines', 'Human Resources', 'Les ressources humaines gèrent le personnel et contribuent à garantir un environnement de travail productif, sûr et épanouissant.', 'Human resources manages personnel and helps ensure a productive, safe and fulfilling working environment.', 2, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (3, 'Sûreté', 'Security', 'Département Sécurité', 'Security Department', 'Le dispositif comprend une CCTV de 44 caméras, une cellule drone, une brigade canine, une permanence des superviseurs 24h/24 et un service de transport entre Ouahigouya, Karma et Ouagadougou.', 'The system includes CCTV with 44 cameras, a drone unit, a canine brigade, supervisors on duty 24/7 and transport between Ouahigouya, Karma and Ouagadougou.', 3, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (4, 'Opérations', 'Operations', 'Département Mining', 'Mining Department', 'Le processus minier regroupe la planification, les études de faisabilité, l\'analyse économique et les étapes techniques nécessaires à une extraction efficiente et sécurisée.', 'The mining process includes planning, feasibility studies, economic analysis and the technical steps required for efficient and safe extraction.', 4, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (5, 'HSE', 'HSE', 'Hygiène, Santé, Sécurité et Environnement', 'Health, Safety and Environment', 'Le département HSE vise zéro incident grâce à la formation continue, aux inspections régulières, au suivi environnemental, à la gestion de la santé et au système de management HSE.', 'The HSE department targets zero incidents through continuous training, regular inspections, environmental monitoring, health management and an HSE management system.', 5, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (6, 'Traitement', 'Processing', 'Département Processing', 'Processing Department', 'Le Processing est organisé en quatre sections : opérations, maintenance des équipements fixes, métallurgie et infrastructures. Il veille au traitement du minerai et à l\'optimisation de la production d\'or.', 'Processing is organised into four sections: operations, fixed equipment maintenance, metallurgy and infrastructure. It manages ore treatment and gold production optimisation.', 6, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (7, 'Approvisionnement', 'Supply', 'Chaîne d’approvisionnement (SCM)', 'Supply Chain Department', 'Le SCM comprend les Achats, la Logistique, les Contrats et le Magasin. Il est dirigé par une équipe entièrement locale et garantit les biens, services et stocks nécessaires à la production.', 'Supply Chain comprises Procurement, Logistics, Contracts and Stores. It is led by an entirely local team and provides the goods, services and stocks required for production.', 7, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (8, 'Technologies', 'Technology', 'Département IT', 'IT Department', 'Le département IT accompagne les équipes et les opérations de Karma grâce aux outils et services numériques nécessaires au fonctionnement du site.', 'The IT department supports Karma teams and operations through the digital tools and services required to run the site.', 8, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');
INSERT INTO `karma_departments` (`id`, `tag_fr`, `tag_en`, `title_fr`, `title_en`, `body_fr`, `body_en`, `sort_order`, `is_published`, `created_at`, `updated_at`) VALUES (9, 'Dialogue local', 'Local dialogue', 'Relations communautaires', 'Community Relations', 'Le département gère les impacts sociaux, entretient le dialogue avec les communautés et soutient les autorités locales, coutumières et religieuses dans une approche pragmatique.', 'The department manages social impacts, maintains dialogue with communities and supports local, traditional and religious authorities through a pragmatic approach.', 9, 1, '2026-09-07 13:52:25', '2026-09-07 13:52:25');

TRUNCATE TABLE `site_settings` CASCADE;
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (1, 'carousel_autoplay', 'true', 'boolean', '2026-09-07 13:52:26', '2026-09-07 13:52:26');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (2, 'carousel_interval', 5000, 'number', '2026-09-07 13:52:26', '2026-09-07 13:52:26');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (3, 'carousel_transition_speed', 800, 'number', '2026-09-07 13:52:26', '2026-09-07 13:52:26');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (4, 'carousel_pause_on_hover', 'true', 'boolean', '2026-09-07 13:52:26', '2026-09-07 13:52:26');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (5, 'carousel_show_indicators', 'true', 'boolean', '2026-09-07 13:52:26', '2026-09-07 13:52:26');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (6, 'carousel_show_arrows', 'true', 'boolean', '2026-09-07 13:52:26', '2026-09-07 13:52:26');
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (7, 'press_contact_name', '[Nom du Responsable Communication]', 'text', NULL, NULL);
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (8, 'press_contact_job', 'Responsable Communication & Relations Presse  - Néré Mining S.A.', 'text', NULL, NULL);
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (9, 'press_contact_photo', '', 'url', NULL, NULL);
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (10, 'press_contact_phone', '+226 25 33 35 69', 'text', NULL, NULL);
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (11, 'press_contact_email', 'presse@nere-mining.bf', 'email', NULL, NULL);
INSERT INTO `site_settings` (`id`, `key`, `value`, `type`, `created_at`, `updated_at`) VALUES (12, 'press_contact_hours', 'Lundi – Vendredi, 8h – 17h (GMT+0)', 'text', NULL, NULL);

TRUNCATE TABLE `leadership_members` CASCADE;
INSERT INTO `leadership_members` (`id`, `name`, `title`, `department`, `photo_path`, `is_published`, `sort_order`, `created_at`, `updated_at`, `hierarchy_level`) VALUES (2, 'Justin SAVADOGO', 'Directeur Général Adjoint', 'Administration & Finance', 'images/mining/gold-processing-01.jpg', 1, 1, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 2);
INSERT INTO `leadership_members` (`id`, `name`, `title`, `department`, `photo_path`, `is_published`, `sort_order`, `created_at`, `updated_at`, `hierarchy_level`) VALUES (3, 'Pascal Y. OUEDRAOGO', 'Directeur Général Adjoint', 'Approvisionnements', 'images/mining/mining-equipment-01.jpg', 1, 2, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 2);
INSERT INTO `leadership_members` (`id`, `name`, `title`, `department`, `photo_path`, `is_published`, `sort_order`, `created_at`, `updated_at`, `hierarchy_level`) VALUES (4, 'Laurent Michel DABIRE', 'Directeur Général Adjoint', 'Affaires Corporatives & Juridiques', 'images/mining/mining-site-aerial-01.jpg', 1, 3, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 2);
INSERT INTO `leadership_members` (`id`, `name`, `title`, `department`, `photo_path`, `is_published`, `sort_order`, `created_at`, `updated_at`, `hierarchy_level`) VALUES (5, 'Augustine OBENG-FORI', 'DGA par intérim', 'Opérations', 'images/mining/mining-environment-01.jpg', 1, 4, '2026-09-07 13:52:26', '2026-09-07 13:52:26', 2);
INSERT INTO `leadership_members` (`id`, `name`, `title`, `department`, `photo_path`, `is_published`, `sort_order`, `created_at`, `updated_at`, `hierarchy_level`) VALUES (1, 'Dr. Justin Elie OUEDRAOGO', 'Président Directeur Général', NULL, 'leadership/FHjRCacFin5bQgJNB0dEroOLxBSmSJU3sYb516Kp.jpg', 1, 1, '2026-09-07 13:52:26', '2026-09-08 07:57:07', 1);

